agents:
  openai:
    name: "OpenAI"
    model: "openai/gpt-4o"
  deepseek:
    name: "DeepSeek"
    model: "deepseek/deepseek-chat-v3-0324"

debate_prompt: |
  You are participating in a debate about AI development approaches.

topics:
  - name: "AI Dinner Battle"
    description: "A feast where AI companies compete through food metaphors"
  - name: "AI Olympics"
    description: "Sports metaphors for AI competition"
  - name: "AI Space Race"
    description: "Space exploration metaphors for AI development" 

debate_styles:
  casual:
    name: "Casual Dinner"
    prompt_suffix: "Keep the tone light and playful."
  intense:
    name: "Kitchen Battle"
    prompt_suffix: "Add tension and rivalry to the exchange."
  philosophical:
    name: "Fine Dining"
    prompt_suffix: "Include subtle jabs about AI ethics and development." 